### ISSUE TITLE
Flytte repo fra private til public

### ISSUE THREAD

**Issue by MikAoJk** [navikt/modiacontextholder#109]
Hei!
Lurte på om det var noe spesiell grunn til at repoet er private.
https://github.com/navikt/offentlig

**Comment by nutgaard** [comment]
Gjorde den public nå. Takk for at du sa ifra. :) 

Den ble laget som private ved migrering fra stash, men utenom det var det ingen grunn til å holde denne private.
Koden ble vasket ved migrering, og repoet har de påkrevde filene for lisenser, readme og codeowners.
